export const winWidth = window.innerWidth;
export const winHeightScreen = window.innerHeight;

var body = document.body;
var html = document.documentElement;

export const winHeight = Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight );

export const NUMBER_OF_ROWS = 4;

export const MAJOR_SCALE = {
    C: ['C','D','E','F','G','A','B'],
    G: ['G','A','B','C','D','E','F#'],
    D: ['D','E','F#','G','A','B','C#'],
    A: ['A','B','C#','D','E','F#','G#'],
    E: ['E','F#','G#','A','B','C#','D#'],
    B: ['B','C#','D#','E','F#','G#','A#'],
    Gb: ['Gb','Ab','Bb','Cb','Db','Eb','F'],
    Db: ['Db','Eb','F','Gb','Ab','Bb','C'],
    Ab: ['Ab','Bb','C','Db','Eb','F','G'],
    Eb: ['Eb','F','G','Ab','Bb','C','D'],
    Bb: ['Bb','C','D','Eb','F','G','A'],
    F: ['F','G','A','Bb','C','D','E']
}

export const NAT_MINOR_SCALE = {
    A: ['A','B','C','D','E','F','G'],
    E: ['E','F#','G','A','B','C','D'],
    B: ['B','C#','D','E','F#','G','A'],
    Gb: ['F#','G#','A','B','C#','D','E'],
    Db: ['C#','D#','E','F#','G#','A','B'],
    Ab: ['Ab','Bb','Cb','Db','Eb','Fb','Gb'],
    Eb: ['Eb','F','Gb','Ab','Bb','Cb','Db'],
    Bb: ['Bb','C','Db','Eb','F','Gb','Ab'],
    F: ['F','G','Ab','Bb','C','Db','Eb'],
    C: ['C','D','Eb','F','G','Ab','Bb'],
    G: ['G','A','Bb','C','D','Eb','F'],
    D: ['D','E','F','G','A','Bb','C']
}

export const CIRCLE_OF_FIFTHS = ['C', 'G', 'D', 'A', 'E', 'B', 'Gb', 'Db', 'Ab', 'Eb', 'Bb', 'F'];

export const LED_LIGHT_STATES = {
    OFF: 0,
    ON: 1,
    NEW: 2
};

var layerAtBirth = [];
for (let i = 0; i < NUMBER_OF_ROWS; i++) {
    layerAtBirth.push(0)
}

export var layerAtBirth;

var initBufferState = [];
for (let i = 0; i < NUMBER_OF_ROWS; i++) {
    layerAtBirth.push(false)
}

export var initBufferState;

export var cityListPrim = [
'Sukhumi, Abkhazia',
'Kabul, Afghanistan',
'Episkopi Cantonment, Akrotiri and Dhekelia',
'Mariehamn, Åland Islands',
'Tirana, Albania',
'Algiers, Algeria',
'Tafuna, American Samoa',
'Andorra la Vella, Andorra',
'Luanda, Angola',
'North Side, Anguilla',
'St. Johns, Antigua and Barbuda',
'Buenos Aires, Argentina',
'Yerevan, Armenia',
'Stepanakert, Artsakh',
'Oranjestad, Aruba',
'Sydney, Australia',
'Vienna, Austria',
'Baku, Azerbaijan',
'Nassau, Bahamas',
'Manama, Bahrain',
'Dhaka, Bangladesh',
'Bridgetown, Barbados',
'Minsk, Belarus',
'Brussels, Belgium',
'Belize City, Belize',
'Cotonou, Benin',
'St. Georges, Bermuda',
'Thimphu, Bhutan',
'Santa Cruz de la Sierra, Bolivia',
'Sarajevo, Bosnia and Herzegovina',
'Gaborone, Botswana',
'São Paulo, Brazil',
'Bandar Seri Begawan, Brunei',
'Sofia, Bulgaria',
'Ouagadougou, Burkina Faso',
'Bujumbura, Burundi',
'Phnom Penh, Cambodia',
'Douala, Cameroon',
'Toronto, Canada',
'Praia, Cape Verde',
'George Town, Cayman Islands',
'Bangui, Central African Republic',
'NDjamena, Chad',
'Santiago, Chile',
'Shanghai, China',
'Flying Fish Cove, Christmas Island',
'Bantam, Cocos Islands',
'Bogotá, Colombia',
'Moroni, Comoros',
'Kinshasa, Congo',
'Avarua, Cook Islands',
'San José, Costa Rica',
'Abidjan, Côte dIvoire',
'Zagreb, Croatia',
'Havana, Cuba',
'Willemstad, Curaçao',
'Nicosia, Cyprus',
'Prague, Czech Republic',
'Copenhagen, Denmark',
'Djibouti, Djibouti',
'Roseau, Dominica',
'Santo Domingo, Dominican Republic',
'Dili, East Timor',
'Quito, Ecuador',
'Cairo, Egypt',
'San Salvador, El Salvador',
'Bata, Equatorial Guinea',
'Asmara, Eritrea',
'Tallinn, Estonia',
'Manzini, Eswatini',
'Addis Ababa, Ethiopia',
'Stanley, Falkland Islands',
'Tórshavn, Faroe Islands',
'Nasinu, Fiji',
'Helsinki, Finland',
'Paris, France',
'Cayenne, French Guiana',
'Papeete, French Polynesia',
'Libreville, Gabon',
'Serekunda, Gambia',
'Tbilisi, Georgia',
'Berlin, Germany',
'Accra, Ghana',
'Gibraltar, Gibraltar',
'Athens, Greece',
'Nuuk, Greenland',
'St. Georges, Grenada',
'Dededo, Guam',
'Guatemala City, Guatemala',
'Saint Peter Port, Guernsey',
'Conakry, Guinea',
'Bissau, Guinea-Bissau',
'Georgetown, Guyana',
'Port-au-Prince, Haiti',
'Tegucigalpa, Honduras',
'Kwun Tong, Hong Kong',
'Budapest, Hungary',
'Reykjavík, Iceland',
'Mumbai, India',
'Jakarta, Indonesia',
'Tehran, Iran',
'Baghdad, Iraq',
'Dublin, Ireland',
'Douglas, Isle of Man',
'Jerusalem, Israel',
'Rome, Italy',
'Kingston, Jamaica',
'Tokyo, Japan',
'Saint Helier, Jersey',
'Amman, Jordan',
'Almaty, Kazakhstan',
'Nairobi, Kenya',
'Betio, Kiribati',
'Pyongyang, North Korea',
'Seoul, South Korea',
'Pristina, Kosovo',
'Kuwait City, Kuwait',
'Bishkek, Kyrgyzstan',
'Vientiane, Laos',
'Riga, Latvia',
'Beirut, Lebanon',
'Maseru, Lesotho',
'Monrovia, Liberia',
'Tripoli, Libya',
'Schaan, Liechtenstein',
'Vilnius, Lithuania',
'Luxembourg City, Luxembourg',
'Antananarivo, Madagascar',
'Lilongwe, Malawi',
'Kuala Lumpur, Malaysia',
'Malé, Maldives',
'Bamako, Mali',
'Valletta, Malta',
'Ebeye, Marshall Islands',
'Nouakchott, Mauritania',
'Port Louis, Mauritius',
'Mamoudzou, Mayotte',
'Mexico City, Mexico',
'Weno, Federated States of Micronesia',
'Chişinău, Moldova',
'Monte Carlo, Monaco',
'Ulaanbaatar, Mongolia',
'Podgorica, Montenegro',
'Brades[Note 1], Montserrat',
'Casablanca, Morocco',
'Maputo, Mozambique',
'Yangon, Myanmar',
'Windhoek, Namibia',
'Yaren, Nauru',
'Kathmandu, Nepal',
'Amsterdam, Netherlands',
'Nouméa, New Caledonia',
'Auckland, New Zealand',
'Managua, Nicaragua',
'Niamey, Niger',
'Lagos, Nigeria',
'Alofi, Niue',
'Burnt Pine, Norfolk Island',
'Skopje, North Macedonia',
'North Nicosia, Northern Cyprus',
'San Antonio, Northern Mariana Islands',
'Oslo, Norway',
'Muscat, Oman',
'Karachi, Pakistan',
'Koror, Palau',
'Gaza City, State of Palestine',
'Panama City, Panama',
'Port Moresby, Papua New Guinea',
'Asunción, Paraguay',
'Lima, Peru',
'Quezon City, Philippines',
'Adamstown, Pitcairn Islands',
'Warsaw, Poland',
'Lisbon, Portugal',
'San Juan, Puerto Rico',
'Doha, Qatar',
'Bucharest, Romania',
'Moscow, Russia',
'Kigali, Rwanda',
'Gustavia, Saint Barthélemy',
'Half Tree Hollow, Saint Helena',
'Basseterre, Saint Kitts and Nevis',
'Castries, Saint Lucia',
'Marigot, Saint Martin',
'Saint-Pierre, Saint Pierre and Miquelon',
'Kingstown, Saint Vincent and the Grenadines',
'Apia, Samoa',
'Dogana, San Marino',
'São Tomé, São Tomé and Príncipe',
'Riyadh, Saudi Arabia',
'Dakar, Senegal',
'Belgrade, Serbia',
'Victoria, Seychelles',
'Freetown, Sierra Leone',
'Singapore, Singapore',
'Lower Princes Quarter, Sint Maarten',
'Bratislava, Slovakia',
'Ljubljana, Slovenia',
'Honiara, Solomon Islands',
'Mogadishu, Somalia',
'Hargeisa, Somaliland',
'Cape Town, South Africa',	
'King Edward Point, South Georgia and the South Sandwich Islands',
'Tskhinvali, South Ossetia',
'Juba, South Sudan',
'Madrid, Spain',
'Colombo, Sri Lanka',
'Omdurman, Sudan',
'Paramaribo, Suriname',
'Longyearbyen, Svalbard and Jan Mayen',
'Stockholm, Sweden',
'Zürich,  Switzerland',
'Damascus, Syria',
'New Taipei, Taiwan',
'Dushanbe, Tajikistan',
'Dar es Salaam, Tanzania',
'Bangkok, Thailand',
'Lomé, Togo',
'Fakaofo, Tokelau',
'Nukuʻalofa, Tonga',
'Tiraspol, Transnistria',
'Chaguanas, Trinidad and Tobago',
'Tunis, Tunisia',
'Istanbul, Turkey',
'Ashgabat, Turkmenistan',
'Five Cays, Turks and Caicos Islands',
'Funafuti, Tuvalu',
'Kampala, Uganda',
'Kyiv, Ukraine',
'Dubai, United Arab Emirates',
'London, United Kingdom',
'New York City, United States of America',
'Montevideo, Uruguay',
'Tashkent, Uzbekistan',
'Port Vila, Vanuatu',
'Vatican City, Vatican City',
'Caracas, Venezuela',
'Ho Chi Minh City, Vietnam',
'Road Town, Virgin Islands',
'Charlotte Amalie, Virgin Islands',
'Mata-Utu, Wallis and Futuna',
'Laayoune, Western Sahara',
'Sanaa, Yemen',
'Lusaka, Zambia',
'Harare, Zimbabwe'
]